src/PortingAssistantExtensionServer/Services/AnalysisService.cs
src/PortingAssistantExtensionTelemetry/TelemetryCollector.cs

fix: repair telemetry metric type

---

src/PortingAssistantVSExtensionClient/Commands/CommandsCommon.cs

more clear instruction for porting assistant cannot be activated issue.

feat: update activation message

---

src/PortingAssistantExtensionServer/Program.cs

fix: add more configuration for serilog

---

src/PortingAssistantExtensionTelemetry/Collector.cs
src/PortingAssistantExtensionTelemetry/Model/ProjectMetrics.cs

feat: add target frameworks into ProjectMetrics

---

src/PortingAssistantExtensionServer/packages.lock.json
src/PortingAssistantExtensionTelemetry/Collector.cs
src/PortingAssistantExtensionTelemetry/packages.lock.json

feat: hash solution file path

---

src/PortingAssistantExtensionServer/Services/AnalysisService.cs
src/PortingAssistantExtensionTelemetry/Collector.cs
src/PortingAssistantExtensionTelemetry/Model/CodeFileMetrics.cs
src/PortingAssistantExtensionTelemetry/Model/MetricsType.cs

feat: add metrics for continuous assessments

---

src/PortingAssistantExtensionServer/Handlers/SolutionAssessmentHandler.cs
src/PortingAssistantExtensionServer/Services/PortingService.cs
src/PortingAssistantVSExtensionClient/Common/ExternalUrls.cs

missing default compatible package version in porting request 
manual test

feat: added default upgrade package version for porting

---

tst/PortingAssistantExtensionIntegTests/Resources/porting-assistant-config.json

update integration test config because server process was crashing and test would not complete.
ran the integration tests in VS and dotnet test command

test: update integ. test config

---

src/PortingAssistantExtensionServer/PortingAssistantExtensionServer.csproj
src/PortingAssistantExtensionServer/packages.lock.json
tst/PortingAssistantExtensionIntegTests/AssessmentTests.cs

feat: bump up porting assistant version

---

src/PortingAssistantExtensionServer/PortingAssistantExtensionServer.csproj
src/PortingAssistantExtensionServer/packages.lock.json
src/PortingAssistantExtensionTelemetry/PortingAssistantExtensionTelemetry.csproj
src/PortingAssistantExtensionTelemetry/packages.lock.json

fix: bump porting assistant version with manifest fix

---

src/PortingAssistantExtensionServer/Common/Constants.cs
src/PortingAssistantExtensionServer/Program.cs

fix: fix typo

---

src/PortingAssistantExtensionClientShared/PortingAssistantExtensionClientShared.projitems
src/PortingAssistantExtensionClientShared/Utils/AwsUtils.cs
src/PortingAssistantExtensionClientShared/Utils/TelemetryClient.cs
src/PortingAssistantExtensionClientShared/Utils/TelemetryConfig.cs
src/PortingAssistantExtensionClientShared/Utils/TelemetryRequest.cs
src/PortingAssistantExtensionServer/PortingAssistantExtensionServer.csproj
src/PortingAssistantExtensionServer/Program.cs
src/PortingAssistantExtensionServer/packages.lock.json
src/PortingAssistantExtensionTelemetry/PortingAssistantExtensionTelemetry.csproj
src/PortingAssistantExtensionTelemetry/Utils/LogUploadUtils.cs
src/PortingAssistantExtensionTelemetry/packages.lock.json
src/PortingAssistantExtensionUnitTest/packages.lock.json
src/PortingAssistantVSExtensionClient2019/PortingAssistantVSExtensionClient2019.csproj
src/PortingAssistantVSExtensionClient2019/packages.lock.json

Include session token to telemetry upload request
Manual testing documented on quip

fix: use session token in telemetry upload

---

.github/workflows/build_test.yml

fix: add hooks to detect git secrets

---

tst/PortingAssistantExtensionUITests/ControlsTest.cs
tst/PortingAssistantExtensionUITests/CustomServerTest.cs
tst/PortingAssistantExtensionUITests/NET6Test.cs
tst/PortingAssistantExtensionUITests/PortingAssistantExtensionUITests.csproj
tst/PortingAssistantExtensionUITests/PortingAssistantExtensionUITests.sln
tst/PortingAssistantExtensionUITests/ProfileTests.cs
tst/PortingAssistantExtensionUITests/VisualStudioSession.cs

Add Invalid Profile Test
Add Test to Switch between Valid Profiles

Add UI Profile tests

---

src/PortingAssistantExtensionClientShared/Commands/SolutionAssessmentCommand.cs

*Issue #, remove the unintended await from code for PA IDE extension.*

fix: Revert the unintended await

---

tst/PortingAssistantExtensionUITests/ControlsTest.cs
tst/PortingAssistantExtensionUITests/ControlsTestVs2022.cs
tst/PortingAssistantExtensionUITests/CustomServerTest.cs
tst/PortingAssistantExtensionUITests/CustomServerTestVs2022.cs
tst/PortingAssistantExtensionUITests/NET6Test.cs
tst/PortingAssistantExtensionUITests/PortingAssistantExtensionUITests.csproj
tst/PortingAssistantExtensionUITests/PortingAssistantExtensionUITests.sln
tst/PortingAssistantExtensionUITests/ProfileTestsVs2022.cs
tst/PortingAssistantExtensionUITests/VisualStudioSession.cs

feat: VS 2022 Setup Tests

---

src/PortingAssistantExtensionServer/Services/AnalysisService.cs

*Issue #195 
Fixed a null reference error during assessment and strengthened accompanying code as well.
Passed all unit tests.

fix: fix null reference error exception.

---

src/PortingAssistantExtensionClientShared/Dialogs/AddProfileDialog.xaml.cs
src/PortingAssistantExtensionClientShared/Utils/AwsUtils.cs
src/PortingAssistantExtensionServer/Program.cs
src/PortingAssistantExtensionTelemetry/Utils/LogUploadUtils.cs
src/PortingAssistantVSExtensionClient2019/PortingAssistantVSExtensionClient2019.csproj
src/PortingAssistantVSExtensionClient2019/packages.lock.json
src/PortingAssistantVSExtensionClient2022/PortingAssistantVSExtensionClient2022.csproj
src/PortingAssistantVSExtensionClient2022/packages.lock.json

Fix: Fix log uploader

---

src/PortingAssistantExtensionClientShared/Dialogs/AddProfileDialog.xaml.cs
src/PortingAssistantExtensionClientShared/Utils/AwsUtils.cs
src/PortingAssistantExtensionServer/Program.cs
src/PortingAssistantExtensionServer/Services/AnalysisService.cs
src/PortingAssistantExtensionTelemetry/Utils/LogUploadUtils.cs
src/PortingAssistantVSExtensionClient2019/PortingAssistantVSExtensionClient2019.csproj
src/PortingAssistantVSExtensionClient2019/packages.lock.json
src/PortingAssistantVSExtensionClient2022/PortingAssistantVSExtensionClient2022.csproj
src/PortingAssistantVSExtensionClient2022/packages.lock.json

telemetry will collect metrics, but only upload when customer turned on share setting

Fix: change uploader behavior

---

src/PortingAssistantExtensionClientShared/Common/UserSettings.cs

fix: fix user setting thread issue in latest vs 2022 version

---

src/PortingAssistantExtensionServer/PortingAssistantExtensionServer.csproj
src/PortingAssistantExtensionServer/packages.lock.json
src/PortingAssistantExtensionTelemetry/PortingAssistantExtensionTelemetry.csproj
src/PortingAssistantExtensionTelemetry/packages.lock.json
src/PortingAssistantExtensionUnitTest/packages.lock.json

update PA Client to 2.1.8
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md) doc
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/porting-assistant-dotnet-ui/blob/develop/CONTRIBUTING.md#commit-your-change)
- [ x] I have updated any necessary documentation, including READMEs and comments (where appropriate)
- [ x] I have added tests that prove my fix is effective or that my feature …

feat: update PA Client to 2.1.8
